"""
Retrieval modes + answer router for BibleGraphRAG.

Modes:
    lookup    - explicit reference (e.g. "Genesis 1:1", "John 3:16-17")
    entity    - questions about a person/place ("who was Moses?")
    theme     - thematic ("verses about forgiveness")
    relation  - two entities ("how is David related to Goliath?")
    semantic  - free-form vector retrieval over verse embeddings
    hybrid    - default, blends entity + semantic

The router asks a small OpenAI chat model to classify intent and extract
refs/entities, then dispatches. The final answer is generated by a larger
model given retrieved verses plus a compact graph context (events, themes,
related entities) — that graph context is what makes this GraphRAG rather
than plain RAG.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Iterator

import networkx as nx
import numpy as np
import pandas as pd
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent / ".env")
if not os.environ.get("OPENAI_API_KEY") and os.environ.get("OPENAI_API"):
    os.environ["OPENAI_API_KEY"] = os.environ["OPENAI_API"]

from openai import OpenAI  # noqa: E402

import bible_graph as bg


ROOT = Path(__file__).parent
DATA_DIR = ROOT / "data"
VERSES_PARQUET = DATA_DIR / "verses.parquet"
EMBED_NPY = DATA_DIR / "verse_embeddings.npy"
GRAPH_JSON = DATA_DIR / "graph.json"

EMBED_MODEL = "text-embedding-3-small"
ROUTER_MODEL = "gpt-4o-mini"
ANSWER_MODEL = "gpt-4o"


# ---------- data classes ----------

@dataclass
class Citation:
    ref: str
    text: str
    verse_id: str


@dataclass
class Answer:
    question: str
    mode: str
    answer: str
    citations: list[Citation] = field(default_factory=list)
    subgraph: nx.MultiDiGraph | None = None
    graph_context: list[str] = field(default_factory=list)
    debug: dict = field(default_factory=dict)


# ---------- main class ----------

class BibleRAG:
    def __init__(
        self,
        verses: pd.DataFrame | None = None,
        embeddings: np.ndarray | None = None,
        graph: nx.MultiDiGraph | None = None,
    ) -> None:
        self.verses = verses if verses is not None else pd.read_parquet(VERSES_PARQUET)
        emb = embeddings if embeddings is not None else np.load(EMBED_NPY)
        # Pre-normalize for fast cosine similarity (dot product = cosine).
        norms = np.linalg.norm(emb, axis=1, keepdims=True)
        self.embeddings = emb / np.maximum(norms, 1e-12)
        self.graph = graph if graph is not None else bg.load_graph(GRAPH_JSON)
        self._w: OpenAI | None = None

    @property
    def w(self) -> OpenAI:
        if self._w is None:
            self._w = OpenAI()
        return self._w

    # ---- retrieval primitives ----

    def embed_query(self, text: str) -> np.ndarray:
        resp = self.w.embeddings.create(model=EMBED_MODEL, input=[text])
        vec = np.asarray(resp.data[0].embedding, dtype=np.float32)
        n = np.linalg.norm(vec)
        return vec / max(n, 1e-12)

    def semantic_topk(self, query: str, k: int = 8) -> list[str]:
        q = self.embed_query(query)
        sims = self.embeddings @ q
        k = min(k, len(sims))
        idx = np.argpartition(-sims, k - 1)[:k]
        idx = idx[np.argsort(-sims[idx])]
        return [
            bg.verse_id(self.verses.iloc[i].book, int(self.verses.iloc[i].chapter), int(self.verses.iloc[i].verse))
            for i in idx
        ]

    # ---- intent router ----

    _ROUTER_SYSTEM = """You classify a user's Bible question and extract structured fields.
Return ONLY a JSON object with keys:
{
  "mode": "lookup" | "entity" | "theme" | "relation" | "semantic" | "hybrid",
  "refs":     [strings like "Genesis 1:1" or "John 3:16-17"],
  "entities": [strings — people or places named in the question],
  "themes":   [strings — abstract topics like "forgiveness", "covenant"]
}
Choose mode:
- "lookup"   if the user gives explicit Bible reference(s) and just wants the text
- "entity"   if the question centers on one person/place ("who was Moses?")
- "theme"    if the question asks about a topic/theme ("verses about love")
- "relation" if the question concerns two named entities and how they relate
- "semantic" if it's a free-form question with no obvious entity or theme keyword
- "hybrid"   if it mixes entity and theme; default when uncertain
"""

    def classify(self, question: str) -> dict:
        # Fast path: explicit reference regex hits
        refs = _scan_refs(question)
        if refs:
            return {"mode": "lookup", "refs": refs, "entities": [], "themes": []}

        resp = self.w.chat.completions.create(
            model=ROUTER_MODEL,
            messages=[
                {"role": "system", "content": self._ROUTER_SYSTEM},
                {"role": "user", "content": question},
            ],
            max_tokens=300,
            temperature=0.0,
            response_format={"type": "json_object"},
        )
        text = ((resp.choices[0].message.content if resp.choices else "") or "").strip()
        try:
            data = json.loads(text)
        except Exception:
            return {"mode": "semantic", "refs": [], "entities": [], "themes": []}
        data.setdefault("mode", "semantic")
        for k in ("refs", "entities", "themes"):
            data.setdefault(k, [])
        return data

    # ---- per-mode retrieval ----

    def retrieve(self, question: str, intent: dict, k: int = 8) -> tuple[list[str], list[str]]:
        """Return (verse_ids, graph_context_lines)."""
        mode = intent.get("mode", "semantic")
        verse_ids: list[str] = []
        ctx: list[str] = []

        if mode == "lookup":
            for ref in intent.get("refs", []):
                verse_ids.extend(bg.verses_by_ref(self.graph, ref))

        elif mode == "entity":
            for ent in intent.get("entities", []):
                vs = bg.verses_mentioning(self.graph, ent)
                verse_ids.extend(vs[:k])
                evs = bg.events_for(self.graph, ent)
                for e in evs[:5]:
                    d = self.graph.nodes[e]
                    ctx.append(f"Event: {d.get('label')} ({d.get('book')} {d.get('chapter')})")
            # Fall back to semantic search if the graph doesn't know this entity yet
            # (e.g. chapter extraction not yet run, or entity is rare).
            if not verse_ids:
                ctx.append("(no entity match in graph; using semantic search)")
                verse_ids.extend(self.semantic_topk(question, k=k))

        elif mode == "theme":
            for th in intent.get("themes", []) or [question]:
                verse_ids.extend(bg.verses_by_theme(self.graph, th)[:k])
            if len(verse_ids) < k:
                verse_ids.extend(self.semantic_topk(question, k=k - len(verse_ids)))

        elif mode == "relation":
            ents = intent.get("entities", [])
            if len(ents) >= 2:
                path = bg.relation_path(self.graph, ents[0], ents[1], max_hops=4)
                if path:
                    ctx.append(f"Path between {ents[0]} and {ents[1]}: " +
                               " -> ".join(self.graph.nodes[n].get("label", n) for n in path))
                    for n in path:
                        if self.graph.nodes[n].get("kind") == "Verse":
                            verse_ids.append(n)
                else:
                    ctx.append(f"(no graph path between {ents[0]} and {ents[1]}; using semantic search)")
            # Always blend in semantic hits for the question, but don't crowd
            # out the relation-path verses.
            remaining = max(0, k - len(verse_ids))
            if remaining:
                verse_ids.extend(self.semantic_topk(question, k=remaining))

        elif mode == "hybrid":
            # Mix entity matches and semantic hits.
            for ent in intent.get("entities", []):
                verse_ids.extend(bg.verses_mentioning(self.graph, ent)[:max(2, k // 3)])
            for th in intent.get("themes", []):
                verse_ids.extend(bg.verses_by_theme(self.graph, th)[:max(2, k // 3)])
            verse_ids.extend(self.semantic_topk(question, k=k))

        else:  # semantic / fallback
            verse_ids = self.semantic_topk(question, k=k)

        # Deduplicate, preserve order, cap at k.
        seen, out = set(), []
        for v in verse_ids:
            if v in seen or v not in self.graph:
                continue
            seen.add(v)
            out.append(v)
            if len(out) >= k:
                break

        # Augment graph context with each verse's themes & events
        themes_seen, events_seen = set(), set()
        for v in out:
            for _, neigh, d in self.graph.out_edges(v, data=True):
                if d.get("kind") == "EXPRESSES":
                    label = self.graph.nodes[neigh].get("label", neigh)
                    if label not in themes_seen:
                        themes_seen.add(label)
                        ctx.append(f"Theme: {label}")
            for u, _, d in self.graph.in_edges(v, data=True):
                if d.get("kind") == "OCCURS_IN":
                    label = self.graph.nodes[u].get("label", u)
                    if label not in events_seen:
                        events_seen.add(label)
                        ctx.append(f"Event: {label}")
        return out, ctx[:25]

    # ---- final answer ----

    _ANSWER_SYSTEM = """You are a careful Bible study assistant grounded in the King James Version provided.
Rules:
- Answer the user's question using ONLY the verses given in the context.
- Cite each claim with the reference in brackets, e.g. [Genesis 1:1].
- If the verses don't fully answer the question, say so plainly. Don't invent verses.
- Keep the answer concise (3-6 sentences) unless the user asks for more.
- The "Graph context" section gives you events, themes, and entity relationships
  derived from the same verses; use them to frame your answer.
"""

    def generate_answer(
        self,
        question: str,
        verses: list[Citation],
        graph_context: list[str],
        max_tokens: int = 600,
    ) -> str:
        verses_block = "\n".join(f"[{c.ref}] {c.text}" for c in verses) or "(no verses retrieved)"
        ctx_block = "\n".join(f"- {line}" for line in graph_context) or "(none)"
        user = (
            f"Question: {question}\n\n"
            f"Verses:\n{verses_block}\n\n"
            f"Graph context:\n{ctx_block}"
        )
        resp = self.w.chat.completions.create(
            model=ANSWER_MODEL,
            messages=[
                {"role": "system", "content": self._ANSWER_SYSTEM},
                {"role": "user", "content": user},
            ],
            max_tokens=max_tokens,
            temperature=0.2,
        )
        return ((resp.choices[0].message.content if resp.choices else "") or "")

    def generate_answer_stream(
        self,
        question: str,
        verses: list[Citation],
        graph_context: list[str],
        max_tokens: int = 600,
    ) -> Iterator[str]:
        verses_block = "\n".join(f"[{c.ref}] {c.text}" for c in verses) or "(no verses retrieved)"
        ctx_block = "\n".join(f"- {line}" for line in graph_context) or "(none)"
        user = (
            f"Question: {question}\n\n"
            f"Verses:\n{verses_block}\n\n"
            f"Graph context:\n{ctx_block}"
        )
        stream = self.w.chat.completions.create(
            model=ANSWER_MODEL,
            messages=[
                {"role": "system", "content": self._ANSWER_SYSTEM},
                {"role": "user", "content": user},
            ],
            max_tokens=max_tokens,
            temperature=0.2,
            stream=True,
        )
        for chunk in stream:
            if not chunk.choices:
                continue
            delta = chunk.choices[0].delta
            content = getattr(delta, "content", None) if delta else None
            if content:
                yield content

    # ---- top-level entry point ----

    def answer(self, question: str, k: int = 8) -> Answer:
        intent = self.classify(question)
        verse_ids, graph_ctx = self.retrieve(question, intent, k=k)
        cits = []
        for v in verse_ids:
            d = self.graph.nodes[v]
            cits.append(Citation(ref=d.get("ref", v), text=d.get("text", ""), verse_id=v))
        if cits:
            ans_text = self.generate_answer(question, cits, graph_ctx)
        else:
            ans_text = ("I couldn't find any verses to ground an answer to that question. "
                        "Try rephrasing, or ask about a specific person, place, or theme.")
        sg = bg.subgraph_for_verses(self.graph, verse_ids, extra_hops=1)
        return Answer(
            question=question,
            mode=intent.get("mode", "semantic"),
            answer=ans_text,
            citations=cits,
            subgraph=sg,
            graph_context=graph_ctx,
            debug={"intent": intent, "n_verses": len(cits)},
        )

    def answer_stream(
        self,
        question: str,
        k: int = 8,
    ) -> Iterator[tuple[str, Any]]:
        """Yield (event_name, payload) tuples so a transport (SSE, websocket,
        whatever) can stream the answer to a client. Order is fixed:
            mode → citation* → graph_context* → subgraph → token* → done.
        On retrieval miss, a single fallback `token` event replaces the model
        call so the client still gets a complete answer.
        """
        intent = self.classify(question)
        yield ("mode", {"mode": intent.get("mode", "semantic")})

        verse_ids, graph_ctx = self.retrieve(question, intent, k=k)

        cits: list[Citation] = []
        for v in verse_ids:
            d = self.graph.nodes[v]
            cits.append(Citation(ref=d.get("ref", v), text=d.get("text", ""), verse_id=v))

        for c in cits:
            yield ("citation", {"ref": c.ref, "text": c.text, "verse_id": c.verse_id})

        for line in graph_ctx:
            yield ("graph_context", {"line": line})

        sg = bg.subgraph_for_verses(self.graph, verse_ids, extra_hops=1)
        if sg.number_of_nodes() > 0:
            sg_json = nx.node_link_data(sg, edges="links")
        else:
            sg_json = {"directed": True, "multigraph": True, "nodes": [], "links": []}
        yield ("subgraph", sg_json)

        if cits:
            for chunk in self.generate_answer_stream(question, cits, graph_ctx):
                yield ("token", {"chunk": chunk})
        else:
            yield ("token", {
                "chunk": (
                    "I couldn't find any verses to ground an answer to that question. "
                    "Try rephrasing, or ask about a specific person, place, or theme."
                ),
            })

        yield ("done", {})


# ---------- helpers ----------

_REF_SCAN = re.compile(
    r"\b(?:[1-3]\s+)?(?:Genesis|Exodus|Leviticus|Numbers|Deuteronomy|Joshua|Judges|Ruth|"
    r"Samuel|Kings|Chronicles|Ezra|Nehemiah|Esther|Job|Psalms?|Proverbs|Ecclesiastes|"
    r"Song of Solomon|Isaiah|Jeremiah|Lamentations|Ezekiel|Daniel|Hosea|Joel|Amos|"
    r"Obadiah|Jonah|Micah|Nahum|Habakkuk|Zephaniah|Haggai|Zechariah|Malachi|"
    r"Matthew|Mark|Luke|John|Acts|Romans|Corinthians|Galatians|Ephesians|Philippians|"
    r"Colossians|Thessalonians|Timothy|Titus|Philemon|Hebrews|James|Peter|Jude|"
    r"Revelation)\s+\d+(?::\d+(?:\s*-\s*\d+)?)?",
    re.IGNORECASE,
)

def _scan_refs(text: str) -> list[str]:
    return [m.group(0).strip() for m in _REF_SCAN.finditer(text)]


# ---------- CLI smoke test ----------

if __name__ == "__main__":
    rag = BibleRAG()

    questions = [
        "Genesis 1:1",                                   # lookup
        "Who was Moses?",                                # entity
        "What does the Bible say about forgiveness?",    # theme
        "How is David related to Goliath?",              # relation
        "What does it mean to be born again?",           # semantic
        "Tell me about the crossing of the Red Sea",     # hybrid
    ]
    for q in questions:
        print("=" * 80)
        print("Q:", q)
        a = rag.answer(q, k=6)
        print(f"mode: {a.mode} | citations: {len(a.citations)}")
        print(f"answer: {a.answer[:400]}")
        print("citations:")
        for c in a.citations[:5]:
            print(f"  [{c.ref}] {c.text[:100]}")
        if a.graph_context:
            print("graph context:")
            for line in a.graph_context[:5]:
                print(f"  - {line}")
        print()
